#                                                                                                                              
#       _____         _____    ____      ______  _______          ____   ____  ____   ____  _____   ______   _________________ 
#   ___|\    \    ___|\    \  |    |    |      \/       \        |    | |    ||    | |    ||\    \ |\     \ /                 \
#  /    /\    \  |    |\    \ |    |   /          /\     \       |    | |    ||    | |    | \\    \| \     \\______     ______/
# |    |  |____| |    | |    ||    |  /     /\   / /\     |      |    |_|    ||    | |    |  \|    \  \     |  \( /    /  )/   
# |    |    ____ |    |/____/ |    | /     /\ \_/ / /    /|      |    .-.    ||    | |    |   |     \  |    |   ' |   |   '     
# |    |   |    ||    |\    \ |    ||     |  \|_|/ /    / |      |    | |    ||    | |    |   |      \ |    |     |   |        
# |    |   |_,  ||    | |    ||    ||     |       |    |  |      |    | |    ||    | |    |   |    |\ \|    |    /   //        
# |\ ___\___/  /||____| |____||____||\____\       |____|  /      |____| |____||\___\_|____|   |____||\_____/|   /___//         
# | |   /____ / ||    | |    ||    || |    |      |    | /       |    | |    || |    |    |   |    |/ \|   ||  |`   |          
#  \|___|    | / |____| |____||____| \|____|      |____|/        |____| |____| \|____|____|   |____|   |___|/  |____|          
#    \( |____|/    \(     )/    \(      \(          )/             \(     )/      \(   )/       \(       )/      \(           
#     '   )/        '     '      '       '          '               '     '        '   '         '       '        '            
#         '                                                                                                                    

#   ___           ___ _            _    _          _       _     _   
#  / __\_   _    / __\ | __ _  ___| | _| | ___ __ (_) __ _| |__ | |_ 
# /__\// | | |  /__\// |/ _` |/ __| |/ / |/ / '_ \| |/ _` | '_ \| __|
#/ \/  \ |_| | / \/  \ | (_| | (__|   <|   <| | | | | (_| | | | | |_ 
#\_____/\__, | \_____/_|\__,_|\___|_|\_\_|\_\_| |_|_|\__, |_| |_|\__|
#       |___/                                        |___/           

#start/time: Time before the hunter begins their hunt. Set to s/m
#start/sound: Sound played at startup. Set to valid minecraft sound
start:
    time: 10s
    sound: entity_wither_death

#join: Nothing
join:
    permissions:
        - autoOp|false
        - canMove|false
        - canBreakBlock|false
        - canPlaceBlock|false

#keepTeam: Allows you to keep current teams before each restart
keepTeam:
    status: false
    item: writable book
    name: "§5Keep Team"

#teamChatPrefix: Default prefix before each message to turn it into a global chat message
teamChatPrefix: "!"

#randomHunterCoordinate: Randomly sends a hunter coordinate in the chat
#randomHunterCoordinate/chance: Chance for a random %
randomHunterCoordinate:
    status: false
    chance: "5"
    item: compass
    name: "§bRandom Hunter Coordinate"

#startHeal: At the start of the game grants a heal to all players
startHeal:
    status: false
    item: golden apple
    name: "§cStarting Heal"

#startFeed: At the start of the game grants satiation to all players
startFeed:
    status: false
    item: steak
    name: "§6Starting Feed"

#startDay: At the start of the game change the world time for the day
startDay:
    status: false
    item: clock
    name: "§eStarting Day"

#startClear: At the start of the game clear all players inventories
startClear:
    status: false
    item: lava bucket
    name: "§dStarting Clear"

#startClearAdvancements: At the start of the game clear all players avancements
startClearAdvancements:
    status: false
    item: empty bottle
    name: "§aStarting Clear Advancements"

#Particles: Tracker with particles (Alpha in development..)
particles:
    status: false
    item: redstone
    name: "§4Particles"

#forge: Automatically cooks all ores upon breaking
#forge/oresXp: When breaking ores releasing experience
forge:
    status: false
    oresXp: false
    item: blast furnace
    name: "§6Forge"

#kits: At the start of the game, give a starting kit to the runners. ⚠ If <> is missing then the base number is 1
# The "<0>" is number of items
#Exemple kit:
#- stone sword <1>
#- stone axe <1>
#- stone pickaxe <1>
#- shield <1>
#- iron helmet <1>
#- iron chestplate <1>
#- iron leggings <1>
#- iron boots <1>
#- steak <64>
kits:
    status: false
    item: iron sword
    name: "§1Kits"
    kit:
        - cooked mutton <32>

#smoker: Automatically cooks the meat of passive mobs and you can personalise loots
smoker:
    status: false
    item: smoker
    name: "§3Smoking"
    cow:
        - leather:1/5
        - steak:1/3
    sheep:
        - white_wool_block:1/2
        - cooked_mutton:1/3
    chicken:
        - feather:1/3
        - cooked_chicken:1/2
    pig:
        - cooked_pork:1/3
    brown_rabbit:
        - cooked_rabbit:1/2
        - rabbit_hide:1/2
        - rabbit_feet:0/1
    salt_and_pepper_rabbit:
        - cooked_rabbit:1/2
        - rabbit_hide:1/2
        - rabbit_feet:0/1
    black_rabbit:
        - cooked_rabbit:1/2
        - rabbit_hide:1/2
        - rabbit_feet:0/1
    hoglin:
        - cooked_pork:1/4
    salmon:
        - cooked_salmon:1/1
    cod:
        - cooked_cod:1/1
    wither:
        - nether_star:1/1
        - netherite_helmet:1/1
        - netherite_chestplate:1/1
        - netherite_leggings:1/1
        - netherite_boots:1/1

#shop: 
shop:
    status: false
    item: emerald
    name: "§aShop"
    deathMoneyLoose: 0.9
    achievementsMoney: 10
    mobs_pig_money: 2
    mobs_sheep_money: 2
    mobs_cow_money: 2
    mobs_chicken_money: 2
    mobs_bat_money: 2
    mobs_bee_money: 2
    mobs_panda_money: 2
    mobs_horse_money: 2
    mobs_axolotl_money: 2
    mobs_cat_money: 2
    mobs_cod_money: 2
    mobs_salmon_money: 2
    mobs_dolphin_money: 2
    mobs_donkey_money: 2
    mobs_fox_money: 2
    mobs_frog_money: 2
    mobs_glow_squid_money: 2
    mobs_llama_money: 2
    mobs_mooshroom_money: 2000
    mobs_ocelot_money: 2
    mobs_parrot_money: 2
    mobs_mule_money: 2
    mobs_polar_bear_money: 2
    mobs_pufferfish_money: 2
    mobs_white_rabbit_money: 2
    mobs_black_rabbit_money: 2
    mobs_salt_and_pepper_rabbit_money: 2
    mobs_snow_golem_money: 500
    mobs_squid_money: 2
    mobs_strider_money: 10
    mobs_tadpole_money: 2
    mobs_trader_llama_money: 2
    mobs_tropical_fish_money: 2
    mobs_villager_money: 2
    mobs_wolf_money: 2
    mobs_iron_golem_money: 20
    mobs_turtle_money: 30
    mobs_blaze_money: 5
    mobs_cave_spider_money: 5
    mobs_creeper_money: 5
    mobs_drowned_money: 5
    mobs_guardian_money: 20
    mobs_hoglin_money: 5
    mobs_husk_money: 5
    mobs_magma_cube_money: 5
    mobs_phantom_money: 5
    mobs_piglin_money: 5
    mobs_pillager_money: 5
    mobs_ravager_money: 5
    mobs_shulker_money: 200
    mobs_skeleton_money: 5
    mobs_slime_money: 5
    mobs_spider_money: 5
    mobs_vindicator_money: 5
    mobs_witch_money: 5
    mobs_wither_skeleton_money: 50
    mobs_zoglin_money: 5
    mobs_zombie_money: 5
    mobs_zombie_villager_money: 20
    mobs_zombified_piglin_money: 5
    mobs_wither_money: 10000
    mobs_warden_money: 20000
    mobs_silver_fish_money: 50
    mobs_wandering_trader_money: 1000
    mobs_stray_money: 100
    mobs_allay_money: 300
    mobs_endermite_money: 150
    mobs_piglin_brute_money: 50
    mobs_zombie_horse_money: 2000
    mobs_skeleton_horse_money: 2000
    mobs_vex_money: 75
    mobs_evoker_money: 50
    ores_copper_ore_money: 1
    ores_coal_ore_money: 3
    ores_iron_ore_money: 5
    ores_gold_ore_money: 9
    ores_redstone_ore_money: 20
    ores_lapis_lazuli_ore_money: 25
    ores_diamond_ore_money: 40
    ores_ancient_debris_money: 250
    ores_nether_gold_ore_money: 2
    blocks_mob_spawner_money: 200
    advancements_obtain_crying_obsidian_money: 10
    advancements_allay_deliver_item_to_player_money: 10
    advancements_froglights_money: 10
    advancements_distract_piglin_money: 10
    advancements_obtain_armor_money: 10
    advancements_very_very_frightening_money: 10
    advancements_lava_bucket_money: 10
    advancements_ride_a_boat_with_a_goat_money: 10
    advancements_kill_dragon_money: 10
    advancements_lightning_rod_with_villager_no_fire_money: 10
    advancements_all_potions_money: 10
    advancements_tame_an_animal_money: 10
    advancements_make_a_sign_glow_money: 10
    advancements_create_beacon_money: 10
    advancements_deflect_arrow_money: 10
    advancements_leash_all_frog_variants_money: 10
    advancements_iron_tools_money: 10
    advancements_brew_potion_money: 10
    advancements_dragon_egg_money: 10
    advancements_kill_mob_near_sculk_catalyst_money: 10
    advancements_fishy_business_money: 10
    advancements_explore_nether_money: 10
    advancements_fall_from_world_height_money: 10
    advancements_ride_strider_money: 10
    advancements_sniper_duel_money: 10
    advancements_root_money: 10
    advancements_levitate_money: 10
    advancements_all_effects_money: 10
    advancements_bullseye_money: 10
    advancements_get_wither_skull_money: 10
    advancements_bred_all_animals_money: 10
    advancements_mine_stone_money: 10
    advancements_two_birds_one_arrow_money: 10
    advancements_enter_the_nether_money: 10
    advancements_whos_the_pillager_now_money: 10
    advancements_upgrade_tools_money: 10
    advancements_walk_on_powder_snow_with_leather_boots_money: 10
    advancements_tactical_fishing_money: 10
    advancements_cure_zombie_villager_money: 10
    advancements_find_end_city_money: 10
    advancements_form_obsidian_money: 10
    advancements_enter_end_gateway_money: 10
    advancements_obtain_blaze_rod_money: 10
    advancements_loot_bastion_money: 10
    advancements_shoot_arrow_money: 10
    advancements_silk_touch_nest_money: 10
    advancements_arbalistic_money: 10
    advancements_respawn_dragon_money: 10
    advancements_smelt_iron_money: 10
    advancements_charge_respawn_anchor_money: 10
    advancements_shiny_gear_money: 10
    advancements_elytra_money: 10
    advancements_tadpole_in_a_bucket_money: 10
    advancements_wax_off_money: 10
    advancements_summon_iron_golem_money: 10
    advancements_avoid_vibration_money: 10
    advancements_return_to_sender_money: 10
    advancements_sleep_in_bed_money: 10
    advancements_dragon_breath_money: 10
    advancements_kill_all_mobs_money: 10
    advancements_enchant_item_money: 10
    advancements_voluntary_exile_money: 10
    advancements_follow_ender_eye_money: 10
    advancements_spyglass_at_parrot_money: 10
    advancements_obtain_netherite_hoe_money: 10
    advancements_totem_of_undying_money: 10
    advancements_kill_a_mob_money: 10
    advancements_adventuring_time_money: 10
    advancements_plant_seed_money: 10
    advancements_find_bastion_money: 10
    advancements_axolotl_in_a_bucket_money: 10
    advancements_allay_deliver_cake_to_note_block_money: 10
    advancements_spyglass_at_dragon_money: 10
    advancements_ride_strider_in_overworld_lava_money: 10
    advancements_trade_at_world_height_money: 10
    advancements_wax_on_money: 10
    advancements_play_jukebox_in_meadows_money: 10
    advancements_hero_of_the_village_money: 10
    advancements_obtain_ancient_debris_money: 10
    advancements_create_full_beacon_money: 10
    advancements_summon_wither_money: 10
    advancements_balanced_diet_money: 10
    advancements_fast_travel_money: 10
    advancements_use_lodestone_money: 10
    advancements_safely_harvest_honey_money: 10
    advancements_trade_money: 10
    advancements_spyglass_at_ghast_money: 10
    advancements_uneasy_alliance_money: 10
    advancements_mine_diamond_money: 10
    advancements_kill_axolotl_target_money: 10
    advancements_find_fortress_money: 10
    advancements_throw_trident_money: 10
    advancements_honey_block_slide_money: 10
    advancements_ol_betsy_money: 10
    advancements_netherite_armor_money: 10
    advancements_enter_the_end_money: 10
    advancements_breed_an_animal_money: 10
    advancements_complete_catalogue_money: 10
    choices:
        dirt:
            size: 1
            cost: 1
        stone:
            size: 1
            cost: 5
        oak_log:
            size: 1
            cost: 5
        iron_ingot:
            size: 1
            cost: 20
        gold_ingot:
            size: 1
            cost: 25
        steak:
            size: 32
            cost: 100
        diamond:
            size: 1
            cost: 100
        totem_of_undying:
            size: 1
            cost: 5000
            special: true
            name: "§7Revive"
            slot: 30
            team: "runners"
        compass:
            size: 1
            cost: 1000
            special: true
            name: "§7Teleporter"
            slot: 32
            team: "hunters"

#rules: Allows you to manage certain rules of your server
rules:
    #rules.tnt: Allows you to manage explosions. Default value is true
    tnt:
        status: true
    #rules.commandBlock: Allows you to manage command blocks. Default value is true
    commandBlock:
        status: true
    #rules.pvp: Allows you to manage pvp. Default value is true
    pvp:
        status: true
