#                                                                                                                              
#       _____         _____    ____      ______  _______          ____   ____  ____   ____  _____   ______   _________________ 
#   ___|\    \    ___|\    \  |    |    |      \/       \        |    | |    ||    | |    ||\    \ |\     \ /                 \
#  /    /\    \  |    |\    \ |    |   /          /\     \       |    | |    ||    | |    | \\    \| \     \\______     ______/
# |    |  |____| |    | |    ||    |  /     /\   / /\     |      |    |_|    ||    | |    |  \|    \  \     |  \( /    /  )/   
# |    |    ____ |    |/____/ |    | /     /\ \_/ / /    /|      |    .-.    ||    | |    |   |     \  |    |   ' |   |   '     
# |    |   |    ||    |\    \ |    ||     |  \|_|/ /    / |      |    | |    ||    | |    |   |      \ |    |     |   |        
# |    |   |_,  ||    | |    ||    ||     |       |    |  |      |    | |    ||    | |    |   |    |\ \|    |    /   //        
# |\ ___\___/  /||____| |____||____||\____\       |____|  /      |____| |____||\___\_|____|   |____||\_____/|   /___//         
# | |   /____ / ||    | |    ||    || |    |      |    | /       |    | |    || |    |    |   |    |/ \|   ||  |`   |          
#  \|___|    | / |____| |____||____| \|____|      |____|/        |____| |____| \|____|____|   |____|   |___|/  |____|          
#    \( |____|/    \(     )/    \(      \(          )/             \(     )/      \(   )/       \(       )/      \(           
#     '   )/        '     '      '       '          '               '     '        '   '         '       '        '            
#         '                                                                                                                    

#   ___           ___ _            _    _          _       _     _   
#  / __\_   _    / __\ | __ _  ___| | _| | ___ __ (_) __ _| |__ | |_ 
# /__\// | | |  /__\// |/ _` |/ __| |/ / |/ / '_ \| |/ _` | '_ \| __|
#/ \/  \ |_| | / \/  \ | (_| | (__|   <|   <| | | | | (_| | | | | |_ 
#\_____/\__, | \_____/_|\__,_|\___|_|\_\_|\_\_| |_|_|\__, |_| |_|\__|
#       |___/                                        |___/           

#start/time: Time before the hunter begins their hunt. Set to s/m
#start/sound: Sound played at startup. Set to valid minecraft sound
start:
    time: 60s
    sound: entity_wither_death

#keepTeam: Allows you to keep current teams before each reset
keepTeam:
    status: false

#teamChatPrefix: Default prefix before each message to turn it into a global chat message
teamChatPrefix: "!"

#startHeal: At the start of the game grants a heal to all players
startHeal:
    status: true

#startFeed: At the start of the game grants satiation to all players
startFeed:
    status: true

#startDay: At the start of the game change the world time for the day
startDay:
    status: true

#startClear: At the start of the game clear all players inventories
startClear:
    status: true

#Particles: Tracker with particles (Alpha in development..)
particles:
    status: false

#forge: Automatically cooks all ores upon breaking
#forge/oresXp: When breaking ores releasing experience
forge:
    status: false
    oresXp: false

#kits: At the start of the game, give a starting kit to the runners. ⚠ If <> is missing then the base number is 1
# The "<0>" is number of items
#Exemple kit:
#- stone sword <1>
#- stone axe <1>
#- stone pickaxe <1>
#- shield <1>
#- iron helmet <1>
#- iron chestplate <1>
#- iron leggings <1>
#- iron boots <1>
#- steak <64>
kits:
    status: false
    kit:
        - cooked mutton <32>

#rules: Allows you to manage certain rules of your server
rules:
    #rules.tnt: Allows you to manage explosions. Default value is true
    tnt:
        status: true
    #rules.commandBlock: Allows you to manage command blocks. Default value is true
    commandBlock:
        status: true
    #rules.pvp: Allows you to manage pvp. Default value is true
    pvp:
        status: true
