data:
    grimhunt:
        load:
            options:
            - "#start/time: Time before the hunter begins their hunt. Set to s/m"
            - "#start/sound: Sound played at startup. Set to valid minecraft sound"
            - "start:"
            - "    time: 10s"
            - "    sound: entity_wither_death"
            - ""
            - "#join: Nothing"
            - "join:"
            - "    permissions:"
            - "        - canMove|false"
            - "        - canBreakBlock|false"
            - "        - canPlaceBlock|false"
            - ""
            - "#keepTeam: Allows you to keep current teams before each restart"
            - "keepTeam:"
            - "    status: false"
            - ""
            - "#teamChatPrefix: Default prefix before each message to turn it into a global chat message"
            - "teamChatPrefix: \"!\""
            - ""
            - "#randomHunterCoordinate: Randomly sends a hunter coordinate in the chat"
            - "#randomHunterCoordinate/chance: Chance for a random %"
            - "randomHunterCoordinate:"
            - "    status: false"
            - "    chance: \"5\""
            - ""
            - "#startHeal: At the start of the game grants a heal to all players"
            - "startHeal:"
            - "    status: false"
            - ""
            - "#startFeed: At the start of the game grants satiation to all players"
            - "startFeed:"
            - "    status: false"
            - ""
            - "#startDay: At the start of the game change the world time for the day"
            - "startDay:"
            - "    status: false"
            - ""
            - "#startClear: At the start of the game clear all players inventories"
            - "startClear:"
            - "    status: false"
            - ""
            - "#startClearAdvancements: At the start of the game clear all players avancements"
            - "startClearAdvancements:"
            - "    status: false"
            - ""
            - "#Particles: Tracker with particles (Alpha in development..)"
            - "particles:"
            - "    status: false"
            - ""
            - "#forge: Automatically cooks all ores upon breaking"
            - "#forge/oresXp: When breaking ores releasing experience"
            - "forge:"
            - "    status: false"
            - "    oresXp: false"
            - ""
            - "#kits: At the start of the game, give a starting kit to the runners. ⚠ If <> is missing then the base number is 1"
            - "# The \"<0>\" is number of items"
            - "#Exemple kit:"
            - "#- stone sword <1>"
            - "#- stone axe <1>"
            - "#- stone pickaxe <1>"
            - "#- shield <1>"
            - "#- iron helmet <1>"
            - "#- iron chestplate <1>"
            - "#- iron leggings <1>"
            - "#- iron boots <1>"
            - "#- steak <64>"
            - "kits:"
            - "    status: false"
            - "    kit:"
            - "        - cooked mutton <32>"
            - ""
            - "#rules: Allows you to manage certain rules of your server"
            - "rules:"
            - "    #rules.tnt: Allows you to manage explosions. Default value is true"
            - "    tnt:"
            - "        status: true"
            - "    #rules.commandBlock: Allows you to manage command blocks. Default value is true"
            - "    commandBlock:"
            - "        status: true"
            - "    #rules.pvp: Allows you to manage pvp. Default value is true"
            - "    pvp:"
            - "        status: true"
        config:
            forge: "§6Forge"
            gui_updater:
                start_heal:
                    lore: "§7At the §2start §7of the game grants a §aheal §7to §eall players§r"
                start_feed:
                    lore: "§7At the §2start §7of the game grants §6satiation §7to §eall players§r"
                start_day:
                    lore: "§7At the §2start §7of the game change the §bworld time §7for the §eday§r"
                start_clear:
                    lore: "§7At the §2start §7of the game §dclear all players inventories§r"
                particles:
                    lore: "§2Tracker §7with §5particles§r"
                forge:
                    lore: "§eAutomatically cooks §dall ores §7upon breaking§r"
                kits:
                    lore: "§7At the §2start §7of the game, §egive §7a §1starting kit §7to the §arunners§r"
                    noKit: "§7§mNo kits found.."
                    kit: "§eCurrent kit:§r"